
spring.application.name=user-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5433/gummi_user_db
spring.datasource.username=gummi_user
spring.datasource.password=gummi_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health
