spring.application.name=talent-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/gummi_talent_db
spring.datasource.username=gummi_user
spring.datasource.password=gummi_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health