services:
  gummi-postgres:
    image: postgres:16
    container_name: gummi-postgres
    restart: always
    environment:
      POSTGRES_DB: gummi_db
      POSTGRES_USER: gummi_user
      POSTGRES_PASSWORD: gummi_password
      POSTGRES_MULTIPLE_DATABASES: gummi_auth_db,gummi_talent_db,gummi_user_db,gummi_proof_db,gummi_project_db
    ports:
      - "5433:5432"
    volumes:
      - gummi_postgres_data:/var/lib/postgresql/data

  gummi-redis:
    image: redis:7
    container_name: gummi-redis
    restart: always
    ports:
      - "6380:6379"

volumes:
  gummi_postgres_data:
