spring.application.name=api-gateway
gummi.services.auth-url=http://localhost:8081
gummi.services.talent-url=http://localhost:8082
gummi.services.user-url=http://localhost:8083
gummi.services.proof-url=http://localhost:8084
gummi.services.project-url=http://localhost:8085
